export const BANNER_ASPECT_WIDTH = 12;
export const BANNER_ASPECT_HEIGHT = 5;
export const BANNER_ASPECT_RATIO = BANNER_ASPECT_WIDTH / BANNER_ASPECT_HEIGHT;

export const BANNER_MAX_WIDTH = 1280;
export const BANNER_DISPLAY_HEIGHT = Math.round(BANNER_MAX_WIDTH / BANNER_ASPECT_RATIO);

export const BANNER_RECOMMENDED_WIDTH = BANNER_MAX_WIDTH;
export const BANNER_RECOMMENDED_HEIGHT = BANNER_DISPLAY_HEIGHT;
